services:
  - type: web
    name: phantompay-backend-pro
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: APP_BASE_URL
        value: https://YOUR_FRONTEND_URL.vercel.app
      - key: DATABASE_URL
        fromService:
          name: phantompay-prodb
          type: postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PHANTOMPAY_FEE_BPS
        value: "100"
      - key: CURRENCY
        value: GBP
    healthCheckPath: /api/health

  - type: postgres
    name: phantompay-prodb
    plan: starter
    ipAllowList: []
    databaseName: phantompay
    user: phantompay_user
